### ISSUE TITLE
invalidateSession results in a 500

### ISSUE THREAD

**Issue by DubHunt** [bombbomb/BBCore#11]
I'm getting a 500 when I call `invalidateSession`:

```
bb = new BBCore({accessToken:'myApiKey'})
...
bb.authenticated
true
bb.invalidateSession()
undefined
2016-11-28 16:35:01.234 api.php:1 POST https://app.bombbomb.com/app/api/api.php 500 (Internal Server Error)
```

Content of the response body for the POST request:
```
{"status":"failure","methodName":"invalidateKey","info":{"errormsg":"Invalid Method"}}
```

**Comment by perl5punk** [comment]
invalidateSession() now relies on logout(), which no longer makes external calls.  Marking this issue as resolved, as of the latest release 4/13/2017
