### ISSUE TITLE
Modifying Array.prototype.find

### ISSUE THREAD

**Issue by carterzenk** [bombbomb/BBCore#23]
While using this library, I was noticing some weird behavior when using `Array.find`.  After some digging, I found this library is re-defining the `Array.find` function on the `Array.prototype`.  This is causing issues with other libraries we are using that are depending on the native implementation of `Array.find`.

[repro link](https://codepen.io/czenk/pen/yEKyZK)

**Comment by gwing33** [comment]
🤦‍♂️ - Why is this not fixed yet?

**Comment by TomPendergrass** [comment]
Fixed in a recent update.
