### ISSUE TITLE
Examples has a getVideos.

### ISSUE THREAD

**Issue by bay-lylekarstensen** [bombbomb/BBCore#26]
In the example the getVideos function has a page of 1.

bbInstance.getVideos({
			page: 1,
			pageSize: 100
		}, function (data) {

This should be page: 0. Your api is Zero based so the videos do not show which causes confusion.

bbInstance.getVideos({
			page: 0,
			pageSize: 100
		}, function (data) {

**Comment by Zoey4560** [comment]
Thanks for catching this. We've updated the examples to match.
