### ISSUE TITLE
macOS Mojave / Chrome - recording does not work.

### ISSUE THREAD

**Issue by bay-lylekarstensen** [bombbomb/BBCore#27]
I have tested both the BBCore and directly from bombomb.com site and the video recorder shows OOPS..
UNKNOWN CAMERA/MICROPHONE ERROR. PLEASE RELOAD

**Comment by bay-lylekarstensen** [comment]
It appears this was an issue with the camera access in Chrome on my computer.

**Comment by Zoey4560** [comment]
Sounds like you found resolution here? If not, I'd suggest contacting our [support team](https://support.bombbomb.com/) for help with your browser permissions.
