### ISSUE TITLE
Support for jQuery no conflict mode

### ISSUE THREAD

**Issue by benwells** [bombbomb/BBCore#3]
Due to conflicts with other plugins, we utilize jQuery's no conflict mode in our application and jQuery is not accessible through the shorthand `$` function. We can only call jQuery methods through the keyword `jQuery`.  When trying to reference bbcore.js in our application, we run into issues because bbcore.js makes use of the `$` shorthand method (`$.ajax`, `$.extend`, and a couple of selectors in the `startVideoRecorder` function).

Do you have a recommended way that we handle this situation?   I was able to work around it for now by downloading and modifying bbcore, but I would definitely prefer to use your CDN link instead of a local version.   Have you all run into this before?  Thanks for your help.

**Comment by perl5punk** [comment]
We worked to remove the jQuery $ dependency, although it seems we're still
getting it cleaned up. $.extend will be replaced, along with $.ajax, which
appear to be the two remaining jQuery references in the library. We'll
leave this open and hopefully get this sorted in the next few weeks.

Cheers,
Brian

**Comment by benwells** [comment]
Thanks for the reply @perl5punk !   That's good to hear.  Would you all consider doing a quick search and replace in the meantime, replacing all instances of `$` with `jQuery`?   This replace is exactly what I'm having to do with my "downloaded and modified" version of bbcore.min.js.   

I would be happy to submit a Pull Request to help out with this effort as well.

**Comment by ehippy** [comment]
we have moved BBCore to using the `jQuery` syntax
