### ISSUE TITLE
Haven't got webhooks response on my site

### ISSUE THREAD

**Issue by saurabh21shukla** [bombbomb/BBCore#7]
Hi,

I am trying to add webhooks on my site By using Add WebHooks method defining in documentation. But unable to configure it.

```
 bbInstance.sendRequest('AddWebHook', {
                hookUrl: 'http://realtyconnection.srmtechsol.com/bbtest/index.html', 
            }, function(result){
                alert("hook Added Successfully"+ result)
            }, function(error){
                alert("hook Added Error");
                console.log(error);
            });
```

Always get error response If I try to add my webpage url ('http://realtyconnection.srmtechsol.com/bbtest/index.html') in Webhooks enable BombBomb option in bombbomb website as sugested in video ('http://support.bombbomb.com/customer/portal/articles/2062941-bombbomb-webhooks?_ga=1.109000907.859055839.1468310427') and try to get response from test Send Webhooks option can't get any response. on my web page url console.  

Please tell me how use webhooks properly on my website to track mails data.

Thanks & Regards
Saurabh Shukla

**Comment by ehippy** [comment]
We've fixed an issue that was keeping your `sendRequest` call from working. You should see the webhooks being created in your account. Do you now see calls from hooks coming in? You can send test webhooks on demand from https://app.bombbomb.com/app/?module=users&page=webhooks
